apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: "HTTP_PORT"
              value: "{{ .Values.env.HTTP_PORT }}"
            - name: "RTMP_PORT"
              value: "{{ .Values.env.RTMP_PORT }}"
            - name: "HLS_API"
              value: "{{ .Values.env.HLS_API }}"
          volumeMounts:
            - mountPath: /opt/data
              name: media-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: back-config
        - name: media-volume
          persistentVolumeClaim:
            claimName: 'media-pvc'
