apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: rtmp
