apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /metrics {
          deny all;
      }
spec:
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "fullname" .)) }}
  rules:
    - host: {{ template "hostname" .Values.service.url }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}-clusteip
              servicePort: 80
